// tests/battle/balance.js — balance pass r2: the journey-measured numbers that supersede MONSTER-BIBLE stat blocks.
// data.js keeps every bible stat block verbatim and applies these on top (the original is kept as `monster.bible`).
//   TWEAKS — hand changes to a few wild monsters' moves (applied before calibration, so the numbers account for them)
//   WILD   — every wild species at its home party level: GENERATED by tests/battle/calibrate.mjs (balance-wild.js)
//   BOSSES — hand-tuned against tests/battle/journey.mjs (whole playthroughs, carried) and its boss-retry table
// See docs/DATA-SHAPES.md §9 for the targets and the before/after numbers.
import { WILD } from './balance-wild.js';

export const TWEAKS = {
  // Muddle turns a child's own party on itself; at 0.7 it decided a third of the Whispering Wood's fights.
  // …and its Whiffle hits the whole party for a flat 6+: two casts, not four.
  hoot_couture: { mp: 6, moves: { muddle: { weight: 0.3 } } },
  jinglebottom: { moves: { muddle_all: { weight: 0.5 } } },
  // Kazapple on everyone for a flat 60+ is a boss's move; it stays, but rarely.
  thunderpuff: { moves: { zapple: { weight: 1.5 }, kazapple: { weight: 0.4 }, bump: { weight: 2 } } },
  // three of them casting Scorcha together was the Belfry's one spike (9 of 30 walk wipes): ones and twos
  candelabracadabra: { group: [1, 2] },
};

/**
 * Bosses at the level a non-grinding child actually reaches them (journey-measured), for 6–10 rounds of "Fight!"
 * that leave the party at roughly 35–55%, while a child who only ever presses Attack still wins within three tries
 * once the rubber band has noticed (S >= 36). EXP is cut where the bible's number threw the next area off the curve.
 */
export const BOSSES = {
  mumbleroot: { partyLevel: 7, hp: 300, atk: 38, exp: 60, moves: { cold_draught: { base: 24 } } },
  sunmane: { partyLevel: 11, exp: 250 },
  // Gulp and the Enormous Burp deal nothing, so he had no way to hurt anyone between Belly Flops: a Tongue Slap
  // (the bible's BUILD already whips his tongue out 2.5 u).
  bogwallop: { partyLevel: 14, hp: 900, atk: 100, def: 40, exp: 400, gold: 300,
    phases: [{ below: 0.4, set: { atk: 110 }, text: '%ACTOR% stands up on his back legs! It is genuinely startling.' }],
    moves: { belly_flop: { recoil: 15, power: 1.0 }, tongue_slap: { name: 'Tongue Slap', kind: 'attack', weight: 3, text: '%ACTOR% slaps %TARGET% with an enormous tongue!' } } },
  sexton_sootbell: { partyLevel: 16, hp: 1000, atk: 80, def: 60, exp: 700, moves: { toll: { base: 45 } } },
  tidewarden: { partyLevel: 18, hp: 1000, exp: 1200, moves: { clamp: { power: 1.2 }, high_tide: { base: 40 } } },
  hoarfax: { partyLevel: 21, hp: 1500, atk: 108, exp: 2000, moves: { frostbreath: { base: 50 }, hush: { targetCaster: true, weight: 1.6 } } },
  iron_governess: { partyLevel: 24, hp: 1600, atk: 130, exp: 2400 },
  hush: { partyLevel: 26, hp: 1900, exp: 1600, moves: { hush_now: { base: 40 } } },
  hark: { partyLevel: 26, hp: 1900, exp: 1600 },
  // A soft old priest: low guard, so every child's swing counts (DEF 128 turned half the party's blows into 1–3);
  // spells slide off him more, and he hushes whoever carries the most magic. Vespers still hurts. One Benediction,
  // not three, and two actions only from half HP.
  mortmain: { partyLevel: 27, hp: 1850, def: 40, mdef: 70, wis: 80, atk: 170, exp: 4000,
    phases: [
      { below: 0.5, set: { actions: 2, name: 'Mortmain Enfolded' }, text: 'The dream wraps round him like a coat. It has given him a bat\'s face, and it is beautiful, and that is worse.' },
      { below: 0.25, text: 'The wings unfurl to their full span. He stops speaking entirely.' }],
    moves: { vespers: { base: 70 }, kascorcha: { weight: 1.5 }, benediction: { amount: 150, maxUses: 1, below: 0.5 },
      silence_the_choir: { targetCaster: true, weight: 2 } } },
  malgrim_cocoon: { partyLevel: 27, hp: 1000, def: 50, mdef: 70, atk: 175, wis: 80, moves: { unlight: { base: 80 } } },
  // "Nothing At All" leaves everyone on one hit point — once it is past half, when it matters — and the moment it
  // gives you is a real one now: somewhere a lullaby, and every hero gets a little colour back, so a child who never
  // heals can still see it through. (Its follow-up never fired before: battle.js now schedules a telegraphed
  // move's `then`.)
  malgrim_unravelling: { partyLevel: 27, hp: 1050, def: 50, mdef: 70, atk: 175, wis: 80,
    moves: { nothing_at_all: { when: 'belowHalf', weight: 2 }, fold: { power: 1.2 }, kascorcha: { weight: 1.5 },
      listen: { kind: 'mercy', pct: 0.3, text: '%ACTOR% tilts its head, as if listening. Somewhere, very softly, someone is humming a lullaby, and everyone gets a little colour back.' } } },
};

function merge(...layers) {
  const out = {};
  for (const layer of layers) {
    for (const [id, patch] of Object.entries(layer)) {
      const cur = out[id] || {};
      out[id] = { ...cur, ...patch, moves: { ...(cur.moves || {}), ...(patch.moves || {}) } };
    }
  }
  return out;
}

export const BALANCE = merge(TWEAKS, WILD, BOSSES);
