import { chromium } from 'playwright';
const url = process.argv[2]; const expr = process.argv[3];
const b = await chromium.launch({args:['--use-angle=metal','--ignore-gpu-blocklist','--enable-gpu','--mute-audio']});
const p = await b.newPage({viewport:{width:1280,height:720}});
p.on('pageerror', e=>console.log('PAGEERR',e.message));
await p.goto(url);
await p.waitForFunction('window.__DQ && __DQ.ready',null,{timeout:30000});
await p.waitForTimeout(800);
const h = await p.evaluate(expr);
console.log(typeof h==='string'?h:JSON.stringify(h,null,1));
await b.close();
